name: Run Script and Commit

# Docs: https://github.com/orgs/community/discussions/26276
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:  # For manual run
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC

jobs:
  run-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run script
        run: |
          # Your script here
          ./update-certificate.bash

      - name: Create random file
        run: |
          RANDOM_FILE="random-$(date +%s)-$RANDOM.txt"
          echo "This is a random file created at $(date)" > "$RANDOM_FILE"
          echo "Created file: $RANDOM_FILE"

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update files [skip ci]" --no-verify
            git push
          else
            echo "No changes to commit"
          fi
        # Prevent running again if commit is made by GitHub Actions
        if: github.actor != 'github-actions[bot]'


